### ISSUE TITLE
Tags showing up with tag ID instead of tag name

### ISSUE THREAD

**Issue by terescode** [terescode/blastcaster-wp#1]
Tags showing up with tag ID instead of tag name

1. Create a post
1. Fill in fields
1. Select any tag
1. Add blast
1. Go to Posts, view post
1. Notice that tag is added with its ID, not name

**Comment by MfgStories** [comment]
If you add a new tag not already in the list the tag displays correctly.  The number only shows up if you select a tag already in the tag list

**Comment by terescode** [comment]
Interesting, I will investigate.

**Comment by terescode** [comment]
@MfgStories deployed to manufacturingstories.com

**Comment by terescode** [comment]
# Root Cause
The category validator was not converting numeric string values to primitive int type so the strings "6", "7" were getting passed to the create post.

# Resolution
Added a "term" sanitizer that performs int conversions on numeric strings and so returns a *mixed* array instead of a string array.

# Removal
This fix will remove the problem.  Should add a regression test for this.  Adding tag needs regression test
