### ISSUE TITLE
Tags & Link Text not showing up in post

### ISSUE THREAD

**Issue by MfgStories** [terescode/blastcaster-wp#11]
I tried this twice to be sure it was not something I was doing wrong.
Blast Screen Shot
![screen shot 2017-01-22 at 11 02 33 am](https://cloud.githubusercontent.com/assets/25268340/22183767/50eddf12-e093-11e6-8f3a-05fb649c632e.png)

Post Screen Shot
![screen shot 2017-01-22 at 11 04 04 am](https://cloud.githubusercontent.com/assets/25268340/22183771/5d27856c-e093-11e6-8c68-a3761e72f27e.png)

**Comment by terescode** [comment]
@MfgStories I deployed two updates to the plugin this weekend.  From the screenshot it looks like you need to clear your cache and refresh your browser to pick them up.  You may also want to try a log out and log in.  Please clear cache/cookies, log out, log in, and try again.  You will know you are seeing the latest updates if you see the new field "Link introduction text" at the bottom (one of the new updates - notice how its not in your screenshot above).

**Comment by terescode** [comment]
Per discussion offline w/ @MfgStories this resolved, closing as invalid
