### ISSUE TITLE
TAGS using new bookmarklet

### ISSUE THREAD

**Issue by MfgStories** [terescode/blastcaster-wp#15]
Turns out the bookmarklet is doing a good job finding tags so lets leave that as is.

However, linking the tag (suggestions) field back to WP really slows things down. Maybe it's because I've built up a lot of tags.  Could we shut off the link back feature for now and just let me add tags as I like using either commas or carriage returns to enter additional tags

**Comment by MfgStories** [comment]
Have tag preview be optional

**Comment by MfgStories** [comment]
Tags preview window does not scroll

**Comment by terescode** [comment]
Moved `Tags preview window does not scroll` to #18

**Comment by terescode** [comment]
Closing this in deference to #21 which describes the story better.
