### ISSUE TITLE
Blaster Posting Error Message 1.26.16

### ISSUE THREAD

**Issue by MfgStories** [terescode/blastcaster-wp#19]
Here is the link to the article
http://firstround.com/review/snag-the-best-advisors-for-your-startup-from-best-selling-authors-to-fortune-500-ceos/

The video is in the same Dropbox

**Comment by MfgStories** [comment]
I closed my browser and reopened and tried again.  This time I did not add any tags.  Results were the same.  Of the two recommended images I chose the left one.  They both looked the same to me.

**Comment by terescode** [comment]
@MfgStories can you post a screenshot of the error here and a link to the dropbox for tracking purposes?

**Comment by MfgStories** [comment]
Here you go.  This also shows up in the second video in the drop box

https://www.dropbox.com/sh/yt3k3a5155rbp07/AAC1BRuqGRulQuIgMd8fegHea?dl=0

![screen shot 2017-01-26 at 1 40 24 pm](https://cloud.githubusercontent.com/assets/25268340/22345175/116399ee-e3cd-11e6-8138-52d3961304a4.png)

**Comment by MfgStories** [comment]
Here is another URL that would not blast
http://www.fabbaloo.com/blog/2017/1/26/one-on-one-with-formlabs-max-lobovsky-part-2
I also noticed that there were two image slots that seemed to be empty between the first and forth image
![screen shot 2017-01-26 at 4 10 05 pm](https://cloud.githubusercontent.com/assets/25268340/22350540/3c77737a-e3e2-11e6-94b8-cc49bae281fd.png)

**Comment by MfgStories** [comment]
This page also caused a posting error.  
https://www.knowatom.com/blog/creating-an-environment-where-challenge-exceeds-skill
![screen shot 2017-01-28 at 10 42 43 am](https://cloud.githubusercontent.com/assets/25268340/22397760/cc9fb8b2-e546-11e6-8262-54db605e8524.png)

**Comment by MfgStories** [comment]
I think the problem may be with the image file name.  Here is a page I tried to Blast
https://www.historyview.org/
It only had one recommended image and I tried to Blast multiple times with the same error.  So I dragged the image out of the blaster window and to my desktop.  As you can see the file name begins with a negative sign [-1.png].  I then tried to Blast the page by uploading the [-1.png] image manually and the Blast worked fine.
![screen shot 2017-01-30 at 9 59 41 am](https://cloud.githubusercontent.com/assets/25268340/22428410/df45f55a-e6d4-11e6-912c-a8df70df3acd.png)

**Comment by terescode** [comment]
There are multiple issues here that should really be addressed with individual tickets.  However...

http://www.fabbaloo.com/blog/2017/1/26/one-on-one-with-formlabs-max-lobovsky-part-2
On this one the image had no extension.  This was resolved by adding some defensive coding that pre-checks the image file type and attempts to determine the extension before passing to wp_handle_sideload.

**Comment by terescode** [comment]
@MfgStories deployed to manufacturingstories.com
