### ISSUE TITLE
Add link prefix/preamble

### ISSUE THREAD

**Issue by terescode** [terescode/blastcaster-wp#3]
Add a field to put text in front of the link text/link url.
Default to "Continue reading at:"
Optional, can be empty
Ideally the default is configurable.

**Comment by terescode** [comment]
@MfgStories are you good with calling this the "link intro"?

**Comment by MfgStories** [comment]
Link Introduction Text

**Comment by terescode** [comment]
@MfgStories this one is complete and deployed to manufacturingstories.com

**Comment by terescode** [comment]
Per discussion with @MfgStories this did not meet acceptance criteria b/c it does not pre-populate the intro text per issue description.  Re-opening to resolve.

**Comment by MfgStories** [comment]
I noticed that the post in WP does not have the (space) after the (:)
Continue reading at:(space)

**Comment by terescode** [comment]
@MfgStories deployed to manufacturingstories.com - if you leave the intro field empty, the post will now default to "Continue reading at:" with space between the intro and the link (customizable in the template).
