### ISSUE TITLE
Surround description with quotes option

### ISSUE THREAD

**Issue by terescode** [terescode/blastcaster-wp#4]
Add an option to surround the description in the post with quotes.

**Comment by terescode** [comment]
This should really be done with styling, not as part of the HTML template.

**Comment by MfgStories** [comment]
After using Blaster for a while I think this enhancement could be added to a wish list for the future or closed all together

**Comment by terescode** [comment]
Moving to backlog

**Comment by MfgStories** [comment]
I think you can close this topic.

**Comment by terescode** [comment]
Closing this one.  No longer a requirement per above.
