### ISSUE TITLE
Add a "see more" prefix at the end of the description

### ISSUE THREAD

**Issue by terescode** [terescode/blastcaster-wp#5]
Add a "see more" prefix at the end of the description
Ideally this is an option in the settings

**Comment by terescode** [comment]
Ellipsis default, should also be done via styling via content property.

**Comment by MfgStories** [comment]
I think you mentioned that adding "see more" was redundant and I agree

I'd like to have the description shown in quotes and add ... 
Example   -  "Bla Bla Bla"...

**Comment by MfgStories** [comment]
After using Blaster for a while I think this enhancement could be added to a wish list for the future or closed all together

**Comment by terescode** [comment]
Read more is provided by default by most themes in archive/index views.  In post view the link intro text would handle this.  Therefore closing this.
